import AppKit
import Observation

struct ClipboardEntry: Identifiable, Equatable {
    var id = UUID()
    var text: String
    var copiedAt: Date
    var preview: String { String(text.split(whereSeparator: { $0.isWhitespace }).joined(separator: " ").prefix(120)) }
    var symbol: String {
        if text.hasPrefix("https://") || text.hasPrefix("http://") { return "link" }
        if text.contains("@"), !text.contains(" ") { return "envelope" }
        if text.contains("\n") { return "text.alignleft" }
        if text.contains("const ") || text.contains("func ") { return "chevron.left.forwardslash.chevron.right" }
        return "textformat"
    }
}

struct ClipboardTail {
    private(set) var entries: [ClipboardEntry] = []
    static let excludedTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
    mutating func capture(_ text: String, types: Set<String>, now: Date = Date()) {
        guard types.isDisjoint(with: Self.excludedTypes), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        entries.removeAll { $0.text == text }
        entries.insert(ClipboardEntry(text: text, copiedAt: now), at: 0)
        if entries.count > 60 { entries.removeLast(entries.count - 60) }
    }
    mutating func clear() { entries.removeAll(keepingCapacity: false) }
}

struct PasteboardSnapshot {
    var items: [[(NSPasteboard.PasteboardType, Data)]]
    init(_ pasteboard: NSPasteboard) {
        items = (pasteboard.pasteboardItems ?? []).map { item in item.types.compactMap { type in item.data(forType: type).map { (type, $0) } } }
    }
    func restore(to pasteboard: NSPasteboard, ifOwnedBy token: String, changeCount: Int) -> Bool {
        guard pasteboard.changeCount == changeCount, pasteboard.string(forType: .pumpkinTemporary) == token else { return false }
        let restored = items.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: type) }
            return item
        }
        pasteboard.clearContents()
        if !restored.isEmpty { pasteboard.writeObjects(restored) }
        return true
    }
}

extension NSPasteboard.PasteboardType {
    static let pumpkinTemporary = NSPasteboard.PasteboardType("app.pumpkin.clipboard.temporary")
}

@MainActor @Observable
final class ClipboardHistory {
    private(set) var tail = ClipboardTail()
    var paused = false
    private(set) var enabled = false
    private(set) var delivering = false
    var message: String?
    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var seen: Int
    @ObservationIgnored private var deliveryRevision = 0
    @ObservationIgnored private var activeLease: (PasteboardSnapshot, String, Int)?
    @ObservationIgnored private var activeCompletion: ((Bool) -> Void)?
    @ObservationIgnored private var sent = false
    var entries: [ClipboardEntry] { tail.entries }
    init(pasteboard: NSPasteboard = .general) { self.pasteboard = pasteboard; seen = pasteboard.changeCount }
    func setEnabled(_ value: Bool) {
        guard value != enabled else { return }
        enabled = value; timer?.invalidate(); timer = nil; seen = pasteboard.changeCount
        if value {
            let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in MainActor.assumeIsolated { self?.poll() } }
            RunLoop.main.add(timer, forMode: .common); self.timer = timer
        } else { cancelDelivery(); clear() }
    }
    func poll() {
        guard pasteboard.changeCount != seen else { return }
        seen = pasteboard.changeCount
        guard enabled, !paused else { return }
        let types = Set((pasteboard.pasteboardItems ?? []).flatMap { $0.types.map(\.rawValue) } + (pasteboard.types ?? []).map(\.rawValue))
        guard pasteboard.string(forType: .pumpkinTemporary) == nil, let text = pasteboard.string(forType: .string) else { return }
        tail.capture(text, types: types)
    }
    func clear() { cancelDelivery(); tail.clear(); message = nil }
    func cancelDelivery() {
        deliveryRevision += 1
        if let (snapshot, token, count) = activeLease, snapshot.restore(to: pasteboard, ifOwnedBy: token, changeCount: count) { seen = pasteboard.changeCount }
        activeLease = nil; delivering = false
        let completion = activeCompletion; activeCompletion = nil
        completion?(sent); sent = false
    }
    func copy(_ entry: ClipboardEntry) {
        pasteboard.clearContents(); pasteboard.setString(entry.text, forType: .string)
        seen = pasteboard.changeCount
    }
    func paste(_ entry: ClipboardEntry, target: NSRunningApplication?, focusedElement: AXUIElement?, completion: @escaping (Bool) -> Void) {
        guard AXIsProcessTrusted(), let target, target.processIdentifier != ProcessInfo.processInfo.processIdentifier else { completion(false); return }
        paste(entry, validate: {
            !target.isTerminated && NSWorkspace.shared.frontmostApplication?.processIdentifier == target.processIdentifier && Self.focusMatches(target.processIdentifier, element: focusedElement)
        }, send: {
            guard let down = CGEvent(keyboardEventSource: nil, virtualKey: 9, keyDown: true), let up = CGEvent(keyboardEventSource: nil, virtualKey: 9, keyDown: false) else { return false }
            down.flags = .maskCommand; up.flags = .maskCommand
            down.postToPid(target.processIdentifier); up.postToPid(target.processIdentifier)
            return true
        }, completion: completion)
    }
    // Revalidate the original field immediately before sending; a changed focus
    // or a newer copy must win over the queued paste and its later restoration.
    func paste(_ entry: ClipboardEntry, validate: @escaping () -> Bool, send: @escaping () -> Bool, completion: @escaping (Bool) -> Void) {
        guard enabled, !delivering, validate() else { completion(false); return }
        let snapshot = PasteboardSnapshot(pasteboard), token = UUID().uuidString
        let item = NSPasteboardItem(); item.setString(entry.text, forType: .string); item.setString(token, forType: .pumpkinTemporary)
        pasteboard.clearContents(); pasteboard.writeObjects([item]); seen = pasteboard.changeCount
        let ownedCount = seen
        activeLease = (snapshot, token, ownedCount); delivering = true
        activeCompletion = completion; sent = false
        deliveryRevision += 1; let revision = deliveryRevision
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) { [weak self] in
            guard let self, self.deliveryRevision == revision else { return }
            guard validate(),
                  self.pasteboard.changeCount == ownedCount,
                  self.pasteboard.string(forType: .pumpkinTemporary) == token else {
                self.cancelDelivery(); return
            }
            guard send() else { self.cancelDelivery(); return }
            self.sent = true
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.6) {
                guard self.deliveryRevision == revision else { return }
                self.cancelDelivery()
            }
        }
    }
    static func focusMatches(_ pid: pid_t, element: AXUIElement?) -> Bool {
        guard let element else { return false }
        var current: CFTypeRef?
        guard AXUIElementCopyAttributeValue(AXUIElementCreateApplication(pid), kAXFocusedUIElementAttribute as CFString, &current) == .success, let current else { return false }
        return CFEqual(element, current) && acceptsPaste(element)
    }
    static func acceptsPaste(_ element: AXUIElement) -> Bool {
        var role: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &role) == .success,
              let role = role as? String, [kAXTextFieldRole, kAXTextAreaRole, kAXComboBoxRole].contains(role) else { return false }
        var writable = DarwinBoolean(false)
        guard AXUIElementIsAttributeSettable(element, kAXValueAttribute as CFString, &writable) == .success, writable.boolValue else { return false }
        var enabled: CFTypeRef?
        if AXUIElementCopyAttributeValue(element, kAXEnabledAttribute as CFString, &enabled) == .success, let enabled = enabled as? Bool, !enabled { return false }
        return true
    }
    deinit { timer?.invalidate() }
    static func requestAccessibility() {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(options)
    }
}
